# Generated by Django 5.1.2 on 2024-10-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fc',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='fc',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fc',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='fc',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='fc',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
